/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SM_Toko_Buku;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Rasito7659
 */
public class mainMenu extends javax.swing.JFrame {

    String id_peg; 
    /**
     * Creates new form mainMenu
     */
    public mainMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public mainMenu(String id_pegawai) {
        initComponents();
        this.setLocationRelativeTo(null);
        id_peg = id_pegawai;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        kasirMenu = new javax.swing.JMenu();
        listMenu = new javax.swing.JMenu();
        listBuku = new javax.swing.JMenuItem();
        listPegawai = new javax.swing.JMenuItem();
        listSupplier = new javax.swing.JMenuItem();
        orderMenu = new javax.swing.JMenu();
        transMenu = new javax.swing.JMenu();
        kategoriMenu = new javax.swing.JMenu();
        logoutMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(1, 50, 67));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 227, 167));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISTEM MANAJEMEN TOKO BUKU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(522, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(253, 227, 167));
        jMenuBar1.setForeground(new java.awt.Color(1, 50, 67));

        kasirMenu.setText("Kasir");
        kasirMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kasirMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(kasirMenu);

        listMenu.setText("List");

        listBuku.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        listBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/book.png"))); // NOI18N
        listBuku.setText("List Buku");
        listBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listBukuActionPerformed(evt);
            }
        });
        listMenu.add(listBuku);

        listPegawai.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        listPegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/person.png"))); // NOI18N
        listPegawai.setText("List Pegawai");
        listPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPegawaiActionPerformed(evt);
            }
        });
        listMenu.add(listPegawai);

        listSupplier.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        listSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cart.png"))); // NOI18N
        listSupplier.setText("List Supplier");
        listSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listSupplierActionPerformed(evt);
            }
        });
        listMenu.add(listSupplier);

        jMenuBar1.add(listMenu);

        orderMenu.setText("Order");
        orderMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(orderMenu);

        transMenu.setText("Transaksi");
        transMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(transMenu);

        kategoriMenu.setText("Kategori");
        kategoriMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kategoriMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(kategoriMenu);

        logoutMenu.setText("Logout");
        logoutMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(logoutMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMenuMouseClicked
        
        loginMenu lm = new loginMenu();
        lm.setVisible(true);
        Connection c = Koneksi.getKoneksi();
        try {
            Statement s = c.createStatement();
            String sql = "UPDATE tb_pegawai SET stat='logout' WHERE id_pegawai='"+id_peg+"'";
        } catch (SQLException ex) {
            Logger.getLogger(mainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false);
        
    }//GEN-LAST:event_logoutMenuMouseClicked

    private void kategoriMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kategoriMenuMouseClicked
        
        kategoriMenu km = new kategoriMenu(id_peg);
        km.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_kategoriMenuMouseClicked

    private void listBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listBukuActionPerformed
        
        bukuMenu bm = new bukuMenu(id_peg);
        bm.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_listBukuActionPerformed

    private void listPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPegawaiActionPerformed
        
        pegawaiMenu pm = new pegawaiMenu(id_peg);
        pm.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_listPegawaiActionPerformed

    private void listSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listSupplierActionPerformed
        
        supplierMenu sm = new supplierMenu(id_peg);
        sm.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_listSupplierActionPerformed

    private void orderMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderMenuMouseClicked
        
        orderMenu om = new orderMenu(id_peg);
        om.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_orderMenuMouseClicked

    private void kasirMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kasirMenuMouseClicked
        
        kasirMenu km = new kasirMenu(id_peg);
        km.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_kasirMenuMouseClicked

    private void transMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transMenuMouseClicked
        
        transaksiMenu tm = new transaksiMenu(id_peg);
        tm.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_transMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu kasirMenu;
    private javax.swing.JMenu kategoriMenu;
    private javax.swing.JMenuItem listBuku;
    private javax.swing.JMenu listMenu;
    private javax.swing.JMenuItem listPegawai;
    private javax.swing.JMenuItem listSupplier;
    private javax.swing.JMenu logoutMenu;
    private javax.swing.JMenu orderMenu;
    private javax.swing.JMenu transMenu;
    // End of variables declaration//GEN-END:variables
}
